apiVersion: apps/v1
kind: Deployment
metadata:
  name: policyconfigdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policymicroservice
  template:
    metadata:
      labels:
        app: policymicroservice
    spec:
      containers:
      - name: policyrepos
        image: mycontainercrr.azurecr.io/policyrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: policymicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: policymicroservice